from pathlib import Path
import json


# Rename JSON y CSV (drag)
def rename_files(ork_file):
    """
    Rename the generated JSON and drag CSV files based on the .ork file name.

    This function takes the name of an OpenRocket (.ork) file and renames the
    generated 'parameters.json' and 'drag_curve.csv' files accordingly. It also
    ensures that no existing files are overwritten by appending a counter if needed.
    Additionally, it removes any existing thrust source file.

    Parameters
    ----------
    ork_file : str or Path
        Path to the .ork file used as reference for naming.

    Returns
    -------
    tuple(Path, Path)
        Paths to the renamed JSON and CSV files.
    """
    ork_file = Path(ork_file)

    json_base = ork_file.stem + "_OPR"
    csv_base = "drag_curve_" + ork_file.stem

    json_original = Path("parameters/rocket/parameters.json")
    csv_original = Path("parameters/rocket/drag_curve.csv")
    thrust_file = Path("parameters/rocket/thrust_source.csv")

    if thrust_file.exists():
        thrust_file.unlink()

    def get_unique_name(path, name, suffix):
        new_path = path.with_name(name + suffix)
        counter = 1
        while new_path.exists():
            new_path = path.with_name(f"{name}({counter}){suffix}")
            counter += 1
        return new_path

    json_new = get_unique_name(json_original, json_base, ".json")
    csv_new = get_unique_name(csv_original, csv_base, ".csv")

    json_original.rename(json_new)
    if csv_original.exists():
        csv_original.rename(csv_new)

    return json_new, csv_new


# check that the file exists 
def verify_file(path):
    """
    Verify that a file exists in the specified path.

    Parameters
    ----------
    path : Path
        Path to the file to be checked.

    Returns
    -------
    bool
        True if the file exists, False otherwise.
    """
    return path.exists()


# Standardize JSON
def standardize_file(route):
    """
    Standardize the structure of a RocketPy JSON file.

    This function reformats the JSON file generated by the serializer to match
    a predefined structure. It renames keys, removes unnecessary fields, and
    restructures nested data such as fins and parachutes.

    Parameters
    ----------
    route : Path
        Path to the JSON file to be standardized.

    Returns
    -------
    dict
        The modified data dictionary after standardization.
    """
    with open(route, "r") as f:
        data = json.load(f)

    # FINS
    for key in list(data.keys()):
        if key.endswith("fins"):
            data["fins"] = data.pop(key, None)

    if "fins" in data and "0" in data["fins"]:
        data["fins"] = data["fins"]["0"]

    # PARACHUTES
    if "parachutes" in data:
        parachutes = data["parachutes"]
        for key in list(parachutes.keys()):
            parachutes["main"] = parachutes.pop(key)
            break


    data.pop("motors", None)
    data["nosecone"] = data.pop("nosecones", None)
    data["airframe"] = data.pop("rocket", None)
    data.pop("id", None)
    data.pop("stored_results", None)
    data.pop("flight", None)
    data.pop("environment", None)
    data.pop("tails", None)

    with open(route, "w") as f:
        json.dump(data, f, indent=4)

    return data


# Check minimum format
def verify_format(data):
    """
    Validate that the JSON data meets the minimum required format.

    This function checks whether essential keys are present and contain valid data.

    Parameters
    ----------
    data : dict
        Dictionary containing the JSON data.

    Returns
    -------
    bool
        True if the data meets the required format, False otherwise.
    """
    required_keys = ["fins", "nosecone", "airframe","parachutes"]
    return all(key in data and data[key] is not None for key in required_keys)


#  Update list in a text file
def update_supported_list(json_path):
    """
    Update the list of supported rocket files.

    This function adds the name of the processed JSON file to a text file
    containing all supported configurations, avoiding duplicates.

    Parameters
    ----------
    json_path : Path
        Path to the JSON file to be recorded.

    Returns
    -------
    None
    """
    txt_path = Path("parameters/supported.txt")

    name = json_path.name

    if txt_path.exists():
        with open(txt_path, "r") as f:
            lines = f.read().splitlines()
    else:
        lines = []

    if name not in lines:
        lines.append(name)

    with open(txt_path, "w") as f:
        for line in lines:
            f.write(line + "\n")


# MAIN PIPELINE
if __name__ == "__main__":
    ork = "parameters/rocket/IREC_version_03.ork"

    json_file, csv_file = rename_files(ork)

    # checking
    if not verify_file(json_file):
        raise ValueError("The JSON was not saved correctly")

    # formatting
    data = standardize_file(json_file)

    # Validation
    if not verify_format(data):
        raise ValueError("The file does not conform to the standard format")

    # update list
    update_supported_list(json_file)

    print("Process completed")